name: Android Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Checkstyle if not present
        run: |
          ./gradlew tasks --all | grep -q checkstyle || \
          ./gradlew dependencies --no-daemon --no-parallel

      - name: Run unit tests
        run: ./gradlew test --no-daemon --no-parallel --stacktrace --info
